-   id: jest
    name: jest
    description: 'Runs all jest test'
    entry: jest --passWithNoTests
    language: node
    types: [javascript]
    args: []
    require_serial: false
    additional_dependencies: ["jest@29.7.0"]
    minimum_pre_commit_version: '0'
